all:
	make exo1
	make exo2
	make exo3
	make exo4

exo1:
	gcc src/exo1.c -o bin/exo1

exo2:
	gcc src/exo2.c -o bin/exo2

exo3:
	gcc src/exo3.c -o bin/exo3

exo4:
	gcc src/exo4.c -o bin/exo4

clear:
	rm bin/*
